DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS ROLE;
CREATE TABLE ROLE(
ID LONG NOT NULL AUTO_INCREMENT,
NAME VARCHAR(50) UNIQUE NOT NULL,
PRIMARY KEY(ID)
);

CREATE TABLE USER (
    ID LONG NOT NULL AUTO_INCREMENT ,
    LOGIN VARCHAR(50) UNIQUE NOT NULL,
    PASSWORD VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) UNIQUE NOT NULL,
    FIRSTNAME VARCHAR(30) NOT NULL,
    LASTNAME VARCHAR(30) NOT NULL,
    BIRTHDAY DATE NOT NULL,
    ROLE_ID LONG NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY (ROLE_ID) REFERENCES role(ID) ON DELETE CASCADE ON UPDATE CASCADE
);